name:                fp-translator
version:             0.1.0.0
github:              "severuscat/fp-translator"
license:             BSD3
author:              "Yanygina Olga"
maintainer:          "severuscat@yandex.ru"
copyright:           "2020 Yanygina Olga"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/severuscat/fp-translator#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  fp-translator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-translator

tests:
  fp-translator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-translator
